project:
  type: website

website:
  title: "My Explorations with LLMs"
  navbar:
    right:
      - icon: github
        href: https://github.com/michaelfuentes10
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


